services:
  orders:
    build: .
    image: weshigbee/consul2-orders
    ports:
      - "3000:3000"
    dns: "192.168.1.132"
      # use host IP to predictably use consul DNS (check firewalls)
      #
      # http://127.0.0.1:3000/orders/report/1
      #   - handler for report uses Service Discovery (via DNS out of the box)
      #  
      # run consul agent such that dns port is listening on DDfM/W host  
      # sudo consul agent -dev -dns-port 53 -client 0.0.0.0 -recursor 1.1.1.1
      # of course register shipments service (wherever it resides), i.e. host port:
      #   consul services register -name shipments -address 192.168.1.132 -port 5000
      #
      # use advertise for implement local service address
      #   sudo consul agent -dev -dns-port 53 -client 0.0.0.0 -advertise 192.168.1.132 -recursor 1.1.1.1
      #   consul services register -name shipments -port 5000
      # FYI deregister demo too
      #   consul services deregister -id shipments
      #   refresh http://127.0.0.1:3000/orders/report/1 # fails again - ISE 500
  #
  # consul:
  #   image: consul
  #   command: [ "agent", "-dev", "-dns-port", "53" ]
  #   ports:
  #     - "8500:8500"
  #     - "8600:53/udp"
  #     - "8600:53/tcp"
