services:
  orders:
    build: .
    image: weshigbee/consul2-orders
    ports:
      - "3000:3000"
    dns: "192.168.1.132" # use host IP to predictably use consul DNS
      # run consul agent such that dns port is listening on DDfM/W host  
      # sudo consul agent -dev -dns-port 53 -client 0.0.0.0 -recursor 1.1.1.1

  # consul:
  #   image: consul
  #   command: [ "agent", "-dev", "-dns-port", "53" ]
  #   ports:
  #     - "8500:8500"
  #     - "8600:53/udp"
  #     - "8600:53/tcp"
