services:

  server1:
    image: consul
    hostname: server1
    volumes:
      - ./conf/server.hcl:/consul/config/server.hcl
    command: [ "agent" ]
    ports:
      - "8500:8500"
    networks:
      default:
        ipv4_address: 10.0.1.20

networks:
  default:
    ipam:
      config:
        - subnet: "10.0.0.0/16"
          gateway: "10.0.0.1"
