services:
  orders:
    build: ./orders/
    image: weshigbee/consul2-orders
    environment:
      SHIPMENTS_URL: "http://shipments:5000" # docker SD
      SMTP_HOST: "mails" # docker SD
    ports:
      - "3000:3000"
  shipments:
    build: ./shipments/src/
    image: weshigbee/consul2-shipments
    ports:
      - "5000:5000"
  mails:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
  tracking:
    build: ./tracking/
    image: weshigbee/consul2-tracking
    ports:
      - "8080:8080"

# disabled shipments -> tracking (env vars configures this)
# - simplify initial demos to just (orders -> shipments)
# - to enable move environment block (below) to shipments service
#environment:
#  MY_SHIPMENTS__TOGGLES__INCLUDETRACKINGINFO: true # can set false to disable too
#  MY_SHIPMENTS__TRACKINGSERVICEURL: http://tracking:8080 # docker SD
