services:
  orders:
    build: ./orders/
    image: weshigbee/consul2-orders
    environment:
      SHIPMENTS_URL: "http://shipments:5000" # docker SD
      SMTP_HOST: "mails" # docker SD
    ports:
      - "3000:3000"
  shipments:
    build: ./shipments/src/
    image: weshigbee/consul2-shipments
    ports:
      - "5000:5000"
  mails:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
  tracking:
    build: ./tracking/
    image: weshigbee/consul2-tracking
    ports:
      - "8080:8080"
